name: "Continuous Integration"

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:

  continuous-integration:
    name: "Continuous Integration"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        install-args: ['', '--prefer-lowest']
        php-version: ['8.1', '8.2']
      fail-fast: false

    steps:
      # Cancel previous runs of the same branch
      - name: cancel
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "xdebug"
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: composer-cache-dir
        id: composercache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: composer-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.json') }}-${{ matrix.install-args }}
          restore-keys: |
            composer-${{ hashFiles('**/composer.json') }}-${{ matrix.install-args }}
            composer-${{ hashFiles('**/composer.json') }}-
            composer-
      - name: "Install dependencies with composer"
        run: |
          composer update ${{ matrix.install-args }} --no-interaction --no-progress --prefer-dist
      - name: "Run tests with phpunit/phpunit"
        run: "vendor/bin/phpunit"